; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stickc_plus2]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	https://github.com/m5stack/M5Unified.git
	bitbank2/AnimatedGIF
	bitbank2/PNGdec
	https://github.com/codeplea/tinyexpr.git
	https://github.com/crankyoldgit/IRremoteESP8266.git
platform_packages = platformio/framework-arduinoespressif32@~3.20016.0
